def position_columns():
    return [
        'alias',
        # 'company_exchange_id',
        'exchange_id',
        'symbol',
        'base_notional',
        'quote_notional',
        'entry_price',
        'unrealised_pnl',
        'liquidation_price',
        'mark_price',
        # 'trade_direction',
        'initial_margin',
        'maintenance_margin',
        # 'pnl_type',
        # 'leverage',
        # 'max_notional',
        # 'row_id',
        # 'position_mode',
        # 'margin_asset',
        # 'margin_type',
        # 'index_price',
        # 'entry_price_base',
        # 'underlying',
        # 'underlying_price',
        # 'delta',
        # 'gamma',
        # 'vega',
        # 'theta',
        # 'rho',
        # 'settlement_price',
        # 'session_pl',
        # 'session_upl',
        # 'mark_price_base',
        # 'quote_index_price',
        # 'update_ms',
        # 'settle_index_price'
    ]
